version: 0.2
phases:
  install:
    commands:
      - echo Installing dependencies...
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 075824682740.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Building Docker image...
      - docker build -t fiap-cluster-devops-ci-cd .
      - docker tag fiap-cluster-devops-ci-cd:latest 075824682740.dkr.ecr.us-east-1.amazonaws.com/fiap-cluster-devops-ci-cd:latest
  post_build:
    commands:
      - echo Pushing Docker image...
      - docker push 075824682740.dkr.ecr.us-east-1.amazonaws.com/fiap-cluster-devops-ci-cd:latest
      # Criação dos arquivo imagedefinitions.json para ser usado no deploy
      - echo '[{"name":"fiap-cluster-devops-ci-cd","imageUri":"075824682740.dkr.ecr.us-east-1.amazonaws.com/fiap-cluster-devops-ci-cd:latest"}]' > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
